# Generated by Django 4.0.6 on 2022-08-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(blank=True, max_length=300)),
                ('state', models.CharField(max_length=300)),
                ('checks', models.BinaryField()),
                ('user_id', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'customers',
                'db_table': 'CUSTOMERS',
            },
        ),
        migrations.CreateModel(
            name='fileuploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('templates', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'fileuploads',
                'db_table': 'TEMPLATES',
            },
        ),
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cid', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'group',
                'db_table': 'GROUP',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=300)),
                ('productName', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('active_date', models.CharField(max_length=300)),
                ('expiry_date', models.CharField(max_length=300)),
                ('payment', models.CharField(max_length=300)),
                ('due_quantity', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'invoice',
                'db_table': 'INVOICE',
            },
        ),
        migrations.CreateModel(
            name='invoice_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=30)),
                ('ContactNumber', models.IntegerField()),
                ('GSTIN', models.CharField(max_length=300)),
                ('PanNo', models.CharField(max_length=300)),
                ('Website', models.CharField(max_length=300)),
                ('Currency', models.CharField(max_length=300)),
                ('CompanyLogo', models.FileField(upload_to='')),
                ('Address', models.CharField(max_length=300)),
                ('BankName', models.CharField(max_length=300)),
                ('BranchName', models.CharField(max_length=300)),
                ('AccountName', models.CharField(max_length=300)),
                ('AccountType', models.CharField(max_length=300)),
                ('BankAccountNo', models.CharField(max_length=300)),
                ('IFSCNo', models.CharField(max_length=300)),
                ('Heading', models.CharField(max_length=300)),
                ('Client', models.CharField(max_length=300)),
                ('Price', models.CharField(max_length=300)),
                ('SubTotal', models.CharField(max_length=300)),
                ('TotalAmount', models.CharField(max_length=300)),
                ('ThankyouMassage', models.CharField(max_length=300)),
                ('FooterNotes', models.CharField(max_length=300)),
                ('UploadYourCompanyStamp', models.FileField(upload_to='')),
                ('TermsandConditions', models.CharField(max_length=300)),
                ('TermsandConditionsDetails', models.CharField(max_length=300)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'invoice_settings',
                'db_table': 'SETTING',
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
                ('user_id', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'product',
                'db_table': 'PRODUCT',
            },
        ),
        migrations.CreateModel(
            name='template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(upload_to='')),
                ('logolink', models.URLField(max_length=300)),
                ('welcomeText', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('buttonname', models.CharField(max_length=300)),
                ('buttonlink', models.URLField(max_length=300)),
                ('description', models.CharField(max_length=3000)),
                ('copyright', models.CharField(max_length=3000)),
                ('user_id', models.IntegerField(default=0)),
                ('file_id', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'template',
                'db_table': 'TEMPLATE',
            },
        ),
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('mobile', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, default=False, max_length=120)),
                ('state', models.CharField(blank=True, default=False, max_length=120)),
                ('Address', models.CharField(blank=True, default=False, max_length=120)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_super', models.BooleanField(default=False, verbose_name='Is super')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Is admin')),
                ('is_client', models.BooleanField(default=False, verbose_name='Is client')),
                ('is_credit', models.IntegerField(blank=True, default=0, verbose_name='Is Credit')),
                ('admin_id', models.IntegerField(blank=True, default=0, verbose_name='admin_id')),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'db_table': 'USERS',
            },
        ),
    ]
